import type { Metadata } from "next";
import { Geist, Poppins, Raleway } from "next/font/google";

import { NotificationBoard, PopupBoard } from "@/core";

import "./globals.css";

import { AppBar, Footer, Sidebar } from "@/shared";
import { AlertNotificationCardSelect, PopupCardSelect } from "services";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const raleway = Raleway({
  weight: ["400", "500", "600", "700"],
  variable: "--font-raleway",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["400", "500", "700"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SmartSyria Horizon",
  // TODO: Figure out app description
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${poppins.variable} ${raleway.variable} antialiased`}
      >
        <div className="app-layout size-full min-h-screen">
          <AppBar className="app-bar" />
          <Sidebar className="sidebar" />
          <main>{children}</main>
          <Footer />
        </div>

        <div className="overlay">
          <NotificationBoard
            NotificationDisplayer={AlertNotificationCardSelect}
          />
          <PopupBoard PopupDisplayer={PopupCardSelect} />
        </div>
      </body>
    </html>
  );
}
