import type { Metadata } from "next";
import { Geist, Poppins, Raleway } from "next/font/google";

import { NotificationBoard } from "@/core";

import "./globals.css";
import { Footer } from "./shared";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const raleway = Raleway({
  weight: ["400", "500", "600", "700"],
  variable: "--font-raleway",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["400", "500", "700"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SmartSyria Horizon",
  // TODO: Figure out app description
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${poppins.variable} ${raleway.variable} antialiased`}
      >
        <main>{children}</main>
        <Footer />

        <div className="overlay">
          <NotificationBoard />
        </div>
      </body>
    </html>
  );
}
